using System.Collections.Generic;
using RimTalk.Data;
using RimTalk.Source.Data;
using Verse;

namespace RimTalk.Prompt;

/// <summary>
/// Prompt rendering context - contains all information needed for parsing.
/// Used by ScribanParser to provide data for templates.
/// </summary>
public class PromptContext
{
    /// <summary>Current primary pawn</summary>
    public Pawn CurrentPawn { get; set; }
    
    /// <summary>All pawns participating in the dialogue</summary>
    public List<Pawn> AllPawns { get; set; }
    
    /// <summary>Current map</summary>
    public Map Map { get; set; }
    
    /// <summary>Variable store</summary>
    public VariableStore VariableStore { get; set; }
    
    /// <summary>Talk request</summary>
    public TalkRequest TalkRequest { get; set; }
    
    /// <summary>Pawn context generated by ContextBuilder</summary>
    public string PawnContext { get; set; }
    
    /// <summary>Dialogue type description (monologue/conversation/urgent, etc.)</summary>
    public string DialogueType { get; set; }
    
    /// <summary>Intent description</summary>
    public string Intent { get; set; }
    
    /// <summary>Topic description</summary>
    public string ConversationTopic { get; set; }
    
    /// <summary>Dialogue status description (initiator's current state)</summary>
    public string DialogueStatus { get; set; }
    
    /// <summary>Full dialogue prompt (result of DecoratePrompt, includes time/weather/location/etc.)</summary>
    public string DialoguePrompt { get; set; }
    
    private List<(Role role, string message)> _simplifiedHistory;
    private List<(Role role, string message)> _rawHistory;
    private string _simplifiedHistoryText;
    private string _rawHistoryText;
    private List<(Role role, string message)> _chatHistory;

    /// <summary>Chat history (Role, Message) - for inserting history in entries</summary>
    public List<(Role role, string message)> ChatHistory
    {
        get
        {
            if (_chatHistory == null)
            {
                _chatHistory = GetChatHistory(simplified: true);
            }
            return _chatHistory;
        }
        set
        {
            _chatHistory = value;
            _simplifiedHistory = value;
            _simplifiedHistoryText = null;
        }
    }

    public List<(Role role, string message)> GetChatHistory(bool simplified)
    {
        if (simplified)
        {
            if (_simplifiedHistory != null) return _simplifiedHistory;
            return _simplifiedHistory = FetchChatHistory(true);
        }

        if (_rawHistory != null) return _rawHistory;
        return _rawHistory = FetchChatHistory(false);
    }

    private List<(Role role, string message)> FetchChatHistory(bool simplified)
    {
        if (AllPawns is { Count: > 0 })
            return TalkHistory.GetMessageHistory(AllPawns, simplified);
        if (CurrentPawn != null)
            return TalkHistory.GetMessageHistory(CurrentPawn, simplified);
        return _chatHistory ?? [];
    }

    public string GetChatHistoryText(bool simplified = false)
    {
        if (simplified)
        {
            if (_simplifiedHistoryText != null) return _simplifiedHistoryText;
            return _simplifiedHistoryText = BuildChatHistoryText(true);
        }
        else
        {
            if (_rawHistoryText != null) return _rawHistoryText;
            return _rawHistoryText = BuildChatHistoryText(false);
        }
    }

    private string BuildChatHistoryText(bool simplified)
    {
        var history = GetChatHistory(simplified);
        if (history != null && history.Count > 0)
        {
            var lines = new List<string>();
            foreach (var (_, message) in history)
            {
                if (string.IsNullOrWhiteSpace(message)) continue;
                lines.Add(message.Trim());
            }

            if (lines.Count > 0)
                return $"{PromptPresetAssembler.ChatHistoryHeader}\n{string.Join("\n", lines)}";
        }

        if (IsPreview)
            return $"{PromptPresetAssembler.ChatHistoryHeader}\n" +
                   "ColonistA: Hello!\n" +
                   "ColonistB: Greetings from RimTalk. This is a placeholder for chat history.";

        return "";
    }

    // Convenience properties - obtained from TalkRequest
    public bool IsMonologue => TalkRequest?.IsMonologue ?? false;
    public TalkType TalkType => TalkRequest?.TalkType ?? TalkType.Other;
    public string UserPrompt => TalkType.IsFromUser() ? TalkRequest?.RawPrompt : null;

    // Compatibility property - Pawns alias
    public List<Pawn> Pawns => AllPawns;
    
    /// <summary>Current pawn index in section iteration (for {{index}} variable)</summary>
    public int ScopedPawnIndex { get; set; }

    /// <summary>Whether this context is being used for preview (e.g. settings menu)</summary>
    public bool IsPreview { get; set; }

    public PromptContext()
    {
        AllPawns = [];
    }

    public PromptContext(Pawn pawn, VariableStore variableStore = null)
    {
        CurrentPawn = pawn;
        AllPawns = pawn != null ? [pawn] : [];
        Map = pawn?.Map;
        VariableStore = variableStore ?? PromptManager.Instance?.VariableStore ?? new VariableStore();
    }

    public PromptContext(List<Pawn> pawns, VariableStore variableStore = null)
    {
        AllPawns = pawns ?? [];
        CurrentPawn = AllPawns.Count > 0 ? AllPawns[0] : null;
        Map = CurrentPawn?.Map;
        VariableStore = variableStore ?? PromptManager.Instance?.VariableStore ?? new VariableStore();
    }

    /// <summary>
    /// Creates context from TalkRequest.
    /// Uses Participants from TalkRequest if available, otherwise falls back to provided pawns list.
    /// </summary>
    public static PromptContext FromTalkRequest(TalkRequest request, List<Pawn> pawns = null)
    {
        // Prefer TalkRequest.Participants (filled in sync layer)
        var participants = request?.Participants ?? pawns ?? new List<Pawn>();
        
        return new PromptContext
        {
            TalkRequest = request,
            AllPawns = participants,
            CurrentPawn = request?.Initiator,
            Map = request?.Initiator?.Map,
            VariableStore = PromptManager.Instance?.VariableStore ?? new VariableStore(),
            // Use data already built in TalkRequest
            PawnContext = request?.Context
            // DialogueType and DialogueStatus are set separately by the caller
            // to avoid pollution from DecoratePrompt which fills request.Prompt with full context
        };
    }
}
